version: '3'
services:
  app_container:
    image: krishz0303/docker-challenge-solved-mohitkjadon:latest
    ports:
      - "80:80"
    networks:
      - app_network

  metrics_scraper:
    image: ubuntu:latest
    command: sh -c "apt-get update && apt-get install -y python3-pip && pip3 install psutil flask && python3 /metrics_scraper.py"
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
